- .env.example
- README.md
- api/index.ts
- components/DataFilter.vue
- components/Feature.vue
- components/Gallery.vue
- components/Map.vue
- pages/gallery.vue
- pages/map.vue
Closes #3.
This PR:
1. Adds a `DataFilter` component which takes a prop `filterField` and matches it with `data` keys to populate the values of a dropdown. Dropdown selection invokes an `emitFilter()` method which then filters the data on the parent component (e.g. Map, Gallery).
2. Allows the `DataFilter` component can be enabled using an environmental var `FRONT_END_FILTERING` and uses an additional env var `FRONT_END_FILTER_FIELD` as the `filterField` key.
3. Adds `DataFilter` to `Map` and `Gallery` components.
I considered having two dropdowns: one to select a column (key), and the other to select values (similar to what [Terrastories](https://github.com/terrastories/terrastories) does). However, I felt that this required more validation with our users, so I opted for this initial …
> Add DataFilter component to allow for basic filtering of data on Views

- .env.example
- README.md
- api/index.ts
- components/Login.vue
- components/Map.vue
- middleware/auth.ts
- nuxt.config.ts
- package.json
- pages/gallery.vue
- pages/login.vue
- pages/map.vue
- tsconfig.json
- yarn.lock
This PR adds authentication, a Login component, JWTs, and a path parameter to bypass logging in.
Specifically:
* `@nuxtjs/auth-next` has been added to handle authentication across the application. This library can sync with any OAuth service so we can use it for more sophisticated authentication in the future. However, for the time being, this is using a singular password (via env var `PASSWORD`).
* Express middleware has been added to handle authentication for any incoming requests. If no token is passed in the header, the page will be redirected to a new component `Login.vue` via a /login/ POST endpoint.
* Successful submission of the right password in `Login.vue` will generate a JWT for authentication across the app, and redirect to `/map`. The JWT is currently not set to expire.
* …
> Implement authentication via JWT using a Login component or path parameter

- pages/gallery.vue
- pages/login.vue
- pages/map.vue
This PR implements several updates to the Vue pages:
* Make API requests when the page is mounted, not created (resolving a temporary server-side error being thrown).
* Decode and show auth0 error description on the login page. This will show messages like the following successful auth0 authentication attempt for a user that has not yet been approved by an auth0 admin to view the app:
> Update Vue pages to better handle retrieval & messaging

- components/DataFilter.vue
- components/Gallery.vue
- components/Map.vue
- package.json
- yarn.lock
This PR adds and customizes a `vue-select` Component for dropdown filtering. `vue-select` is a great, feature rich select/dropdown/typeahead component Vue component. I am using it here to allow the user to do filtering using multiple selections, and to add a colored dot next to each selection that matches what is shown for the dots on the map. I also cleaned up some parts of both the `Map` and `Gallery` components.
> Implement and style vue-select component

- .env.example
- README.md
- api/index.ts
- components/Auth0Login.vue
- components/PasswordLogin.vue
- middleware/authMiddleware.ts
- nuxt.config.ts
- pages/index.vue
- pages/login.vue
Closes https://github.com/ConservationMetrics/guardianconnector-views/issues/15.
This PR is ironing out some past work to support different authentication methods: password with JWT, and auth0.
Instead of supporting one over the other wholesale, we are instead giving the administrator the option to define their authentication strategy: auth0, password, or none.
Depending on which strategy is chosen, the end user will have to log in via `Auth0Login.vue`, `PasswordLogin.vue`, or never have to log in (and be redirected away from the `/login` route if accessed) - respectively.
Authentication middleware has been adapted and streamlined in accordance to the requirements of the three strategies.
> Make it possible to set an authentication strategy (auth0, password, or none)

- api/index.ts
- api/utils/dataProcessing.ts
- components/Alerts.vue
- components/Feature.vue
- components/FeaturePopup.vue
- components/Gallery.vue
- components/Map.vue
- components/Media.vue
- pages/alerts/_tablename.vue
- src/utils.ts
Checks one off the list on #16 by implementing the `FeaturePopup` component to show alert properties, links, and an embedded image for change detection alerts.
* Modified the `alerts/` API endpoint to use a `prepareChangeDetectionData()` function to format the properties key/value pairs to more legible to humans, discarding the ones that are not useful to the end user, and depending on if the view has media embedding & linking to GCCD resources turned on, creates links to some of the assets for embedding or linking.
* Added event listeners for the alert map features (similar to how it's done in the `Map` component).
* In `Feature`, conditionally render GCCD preview map link if provided.
* Some other minor stylistic and naming fixes here and there.
> Create and structure `FeaturePopup` for alerts

- api/index.ts
- api/utils/dataProcessing.ts
- components/Alerts.vue
- components/Feature.vue
- components/FeaturePopup.vue
- components/Map.vue
- components/Media.vue
Contributes to https://github.com/ConservationMetrics/guardianconnector-views/issues/16 by contributing the following:
* The API endpoint for alerts now provides two GeoJSON arrays, `mostRecentAlerts` and `otherAlerts` based on the date given in the data, so as to be able to style the most recent alerts differently from the others.
* `selectedFeature` state management has been expanded to store the ID and source of the layer, to be able to highlight a feature with a different color when clicked (selected), and returned back to the original color when deselected (by closing the `FeaturePopup` or clicking another feature).
* Ideally should have been a different PR but -- Added image captions for the `sat_viz_detec` T1 JPG image used in the `FeaturePopup` with a lookup table of commonly used …
> Add dynamic color changes to features based on date and `SelectedFeature` state

- components/Alerts.vue
- components/Download.vue
- components/FeaturePopup.vue
Another one for https://github.com/ConservationMetrics/guardianconnector-views/issues/16: 
* I added a function `calculateCentroid()` to generate a geographic centroid for the alerts. (I know one of our users likes to copy and paste lat/long into Google Maps so as to bookmark the places, and this will enable them to do so.)
* I added a new component `Download` which provides the ability to download an individual alert as CSV or GeoJSON.
> Add `Download` component with CSV/GeoJSON buttons and geographic centroid to `Feature`

- components/Alerts.vue
- package.json
- yarn.lock
Contributes to https://github.com/ConservationMetrics/guardianconnector-views/issues/16 by adding animated pulsating circles around the latest batch of alerts, to draw the user's attention to the most recent data. `addPulsatingCircles()` is called and once the map is idle (e.g. data has been loaded), it draws map markers around the bbox of the data.
> Add pulsating circles over new alerts

- components/Alerts.vue
- components/AlertsIntroPanel.vue
- components/Download.vue
- components/FeaturePopup.vue
Closes https://github.com/ConservationMetrics/guardianconnector-views/issues/16 (insofar as it ticks the last item off the list!)
This PR uses the `Download` component that was added previously to allow the user to download all of the data as CSV or GeoJSON in the `AlertsIntroPanel` view. 
`Download` now has separate `downloadAlertCSV` / `downloadAlertGeoJSON` and `downloadAllCSV` / `downloadAllGeoJSON` functions, and a `typeOfData` prop passed by an upstream component determines which one is run. (In order to parse the data differently depending on which kind of dataset is passed to it, a singular alert or the entire alert dataset.)
> Add download all alerts buttons to `AlertsIntroPanel`

- components/AlertsDashboard.vue
- components/Map.vue
- components/Sidebar.vue
This PR implements responsive design for the Sidebar (formerly FeaturePopup) by allocating it 50% of the bottom of the screen for smaller viewports. Also added is a pulsing arrow to cue the user to scroll down.
> Responsive design for Sidebar (with pulsing arrow as cue to scroll)

- api/dataProcessing/helpers.ts
- api/dataProcessing/transformData.ts
- components/AlertsDashboard.vue
This PR resolves a minor bug where the geographic centroid for MultiPolygon features was shown in the dashboard as "NaN, NaN" because the ` calculateCentroid()` function was only set up to handle single Polygon GeoJSON features. 
Now, the function (which has been moved to take place server-side, and converted to TypeScript) checks if the incoming coordinates are MultiPolygon (3 dimensional array) versus Polygon (array of array) and applies additional flattening for the former.
> Handle geographic centroid calculation for MultiPolygon geometries

- api/dataProcessing/transformData.ts
- api/dataProcessing/types.ts
Taking up a good suggestion by @mmckown in Suriname, this PR adapts the `prepareAlertStatistics` API function to provide cumulative data for the alerts dashboard.
Before:
After:
* I created a helper function `updateCumulativeData` that cumulatively sums either alerts or hectares for each month, and use that function to populate `alertsPerMonth` and `hectaresPerMonth`.
* Some unrelated linting changes made their way in, reminding me that I need to apply auto-linting on commits for this repo.
* Moved a TypeScript type used in the function to `types.ts` to be consistent.
> `prepareAlertStatistics` provides cumulative data for alerts per month

- components/AlertsDashboard.vue
Closes https://github.com/ConservationMetrics/guardianconnector-views/issues/41. This PR implements a quick fix to exclude adding event listeners to the alert layers that add a stroke to a polygon, thereby causing the buggy behavior described in #41.
> Don't apply mouse event listeners to alert layers that add a stroke for a polygon

- api/dataProcessing/transformData.ts
- api/index.ts
- components/AlertsDashboard.vue
- components/AlertsIntroPanel.vue
- components/MapLegend.vue
- src/mapFunctions.ts
Closes https://github.com/ConservationMetrics/guardianconnector-views/issues/43.
To add alerts from the Alerts Dashboard component to the Map Legend, and to improve the legend graphic for polygons and point geometries.
Linestring alerts - before & after
Polygon alerts - before & after
* Renamed `otherAlerts` to `previousAlerts` in a bunch of places for purposes of clear and consistent naming. Also renamed `recentAlerts` to `mostRecentAlerts`.
* On the `AlertsDashboard` component, add the alerts map legend layer IDs to be included in the string of layer IDs to be processed by `prepareMapLegendLayers`.
* Modify the CSS props for the polygon and circle geometries to better resemble how they might look on the map.
> Add alerts to map legend, and improve graphic for geometry type

- components/AlertsDashboard.vue
- components/Download.vue
Closes https://github.com/ConservationMetrics/guardianconnector-views/issues/49.
* Fixed some var names that were not yet updated for the refactor work in https://github.com/ConservationMetrics/guardianconnector-views/pull/45.
> Patch: Fix alerts date slider, and download buttons for all data

- api/config.ts
- api/index.ts
- components/AlertsDashboard.vue
- components/Feature.vue
- components/Sidebar.vue
- docs/config.md
- pages/alerts/_tablename.vue
Closes #56.
We are now providing a separate media path where alerts are found, as distinct from Mapeo data. 
Also, I implemented a fix for providing filepaths for Mapeo observations that have multiple attachments.
> Separate media paths for alerts & mapeo data on `AlertsDashboard`

- components/shared/DataFilter.vue
- package-lock.json
- package.json
Now that [`vue3-select-component` allows a custom option slot for #value when `isMulti` is set](https://github.com/TotomInc/vue3-select-component/issues/128), this PR re-adds the selected colored dots shown on the map into the listbox for our `DataFilter` component, as we had them in the Vue 2 select component.
* Bumped `vue3-select-component` to 0.7.0.
* Adapted HTML and CSS for the listbox template to show colored dots and style the option boxes similar to what we had before.
> Implement custom multi tag for Vue 3 Select component

- components/AlertsDashboard.vue
- components/shared/BasemapSelector.vue
- package-lock.json
- package.json
Closes https://github.com/ConservationMetrics/guardianconnector-explorer/issues/84 by adding [`mapbox-gl-ruler-control`](https://github.com/ardhi/mapbox-gl-ruler-control) to the AlertsDashboard component.
* Installed `mapbox-gl-ruler-control` library.
* Implemented the control on `AlertsDashboard` with a few custom style rules to make it look similar to our other map controls.
* Introduced a reactive var `hasRulerControl` (Boolean) to ensure our custom basemap picker control shows up underneath the ruler, if used.
Writing custom Mapbox code to handle all of this [ala Mapbox's example](https://docs.mapbox.com/mapbox-gl-js/example/measure/). The new library introduced here is pretty lightweight, and while it hasn't been updated in 2 years or doesn't have many repository stars, [the …
> Add `mapbox-gl-ruler-control` to AlertsDashboard component

- components/AlertsDashboard.vue
- components/MapView.vue
Closes https://github.com/ConservationMetrics/guardianconnector-explorer/issues/85. I found that simply increasing the `circle-radius` and `circle-stroke-width` made a substantial difference. I opted to not increase the radius as much on `AlertsDashboard` because doing so causes the Mapeo points to obscure the alerts, which are just as important in the visual hierarchy of that view.
Map:
Alerts:
Bumped up `circle-radius` and `circle-stroke-width`
> On map views, increase point radius and stroke-width

- components/shared/DataFilter.vue
- lang/en.json
- lang/es.json
- lang/nl.json
- lang/pt.json
Closes https://github.com/ConservationMetrics/gc-explorer/issues/80. Makes it possible for a user to select "No column entry" in the filter dropdown to add data for which the filter column value is null or undefined.
* In mapping data values for `filterColumn`, if the value is null or undefined then return an object with an undefined `value`, `noColumnEntry` (i18n string) `label`, and `color`.
* When creating a `uniqueFilterValues` map, if this object is found, then add it to the very end of the list.
* Set fallback value for `defaultColoredDotColor` to `#808080` (a neutral gray).
* I also refactored the code for improved legibility by choosing better names for variables and functions throughout.
> Refactor `DataFilter` component to allow filtering of data where filterColumn is not set

- components/shared/BasemapSelector.vue
- docs/config.md
- i18n/locales/en.json
- i18n/locales/es.json
- i18n/locales/nl.json
- i18n/locales/pt.json
- utils/mapFunctions.ts
Closes https://github.com/ConservationMetrics/gc-explorer/issues/96. 
This PR updates the Tile URL structure for Planet monthly basemaps from NICFI, which is no longer available, to PlanetScope Select. 
This will enable Project Centinela (or paying) users to access Planet monthly basemaps again.
> Switch out "Planet NICFI" tile URL for "PlanetScope Select"

- components/AlertsDashboard.vue
- e2e/alerts.spec.ts
Fix E2E test reliability by adding explicit waiting for map rendering in the alerts dashboard test. Closes #133 
https://github.com/user-attachments/assets/0a6375c5-1956-40c4-a150-1f70229da5f9
- **Added map style and map loading checks**:   Added explicit waiting mechanisms to ensure the map is fully rendered before test interactions. Wait for `map.isStyleLoaded()` and `map.isLoaded` before proceeding.
- Not changing the core map functionality or rendering logic
- Not modifying the alerts dashboard component behavior
> Resolve "bug: Alerts e2e test passing early"

- README.md
- e2e/index.spec.ts
Add comprehensive render / E2E tests for the home page to ensure core functionality works correctly. Closes #128 
- Added `e2e/index.spec.ts` with two test suites:
- **Page rendering test**: Verifies the home page loads properly with logo, heading, and alerts links
- **Language picker test**: Tests language switching functionality with resilient selectors that survive styling changes
- Unit testing the index since it is technically not a Nuxt page not its standalone component (too complex with Nuxt dependencies)
> Add Render / E2E tests for home page functionality

- server/database/dbConnection.ts
When running `main` locally, I got an unexpected error
```
ERROR  Error fetching config on API side: Cannot read properties of null (reading 'query')
Setting up database connection to guardianconnector...
Config database does not exist. Attemping to create...
```
This is because the recently merged code for running tests in CI set a boolean incorrectly. Also, I improved the console log message to get a better grip of what is going on.
> fix: set correct boolean value for skipping config db creation in CI

- components/AlertsDashboard.vue
- components/shared/MapLegend.vue
- e2e/01-alerts.spec.ts
- types/types.ts
Closes https://github.com/ConservationMetrics/gc-explorer/issues/163.
This PR solves the issue described in #163, and also provides a solution for an as-of-yet undocumented issue where either a linestring, point, or polygon is used to represent alerts in the legend, when there may be multiple geometries on the map.
Before (note the polygon on the map, which the line in the legend does not represent well):
After:
```
=== Testing Most recent alerts ===
Found 4 layers: [
'most-recent-alerts-polygon',
'most-recent-alerts-polygon-stroke',
'most-recent-alerts-linestring',
'most-recent-alerts-symbol'
]
✅ 4 layers initially visible
✓ most-recent-alerts-polygon is hidden
✓ most-recent-alerts-polygon-stroke is hidden
✓ most-recent-alerts-linestring is hidden
✓ most-recent-alerts-symbol is hidden
✓ …
```
> fix: on alerts dashboard, toggle show/hide alert layers as a group

- components/AlertsDashboard.vue
To add a final fix for https://github.com/ConservationMetrics/gc-explorer/issues/163 - removing pulsing circles when most recent alerts are toggled off in the legend, and adding them again when toggled on.
> Also remove pulsing circle when deactivating most recent alerts

- server/db/migrations/0001_rename_config_to_view_config.sql
- server/db/migrations/meta/0001_rename_config_to_view_config.json
Fix idempotent migration for config table rename
N/A
- Updated migration SQL to use `DO $$ BEGIN IF EXISTS (...) AND NOT EXISTS (...) THEN ALTER TABLE ... END IF; END $$;` block which basically checks that config exists and view_config does not THEN alters
- Updated migration metadata to match the new SQL content
- Made migration safe to re-run without errors
- Not changing any other functionality
- Not modifying existing schemas
> Drizzle Migration HotFix: Fix idempotent migration for config table rename

- components/config/ConfigPermissions.vue
- middleware/oauth.global.ts
- pages/index.vue
- server/api/auth/auth0.get.ts
- types/types.ts
- utils/auth.ts
Fix the bug where public (i.e. dataset with `anyone` permissions) datasets were asking for log in. Closes #210 and a bug around view routes not rendering because the permission requirements were too high Closes #189. 
- Default permissions is `signed-in`
- Role already defaulted to "Viewer"
- Fix type casting which was using outdated variable i.e. `routeLevelPermission` -> `ROUTE_LEVEL_PERMISSION`
> Bug: Public datasets still asking for login & Bug: View Routes do not resolve without auth0 role

- .github/pull_request_template.md
- CONTRIBUTING.md
By submitting a pull request to this project, you agree to license your contribution under the terms of the MIT License.
Please read our [Contributor License Agreement and other Contributing Guidelines](CONTRIBUTING.md).
Share core contributing guidelines from one source of truth (in gc-scripts-hub)
- added reference to gc-scripts-hub, and removed duplicative content from here.
- kept special guidance around test frameworks
None
> Reference shared CONTRIBUTING and add LLM disclosure
